language: python
sudo: false
python:
  - '3.5'

cache:
  directories:
    - node_modules

before_install:
  - pip install --upgrade pip
  - pip install pylama
  - pip install lizard
  - nvm install 5.1
  - node -v
  - npm -v

install:
  - (cd ./js-sdk; npm install)

script:
  - pylama plugin
  - lizard plugin -C 10 -w -i 0
  - (cd ./js-sdk; npm run lint)

notifications:
  slack:
    secure: "UVurLgQkuXG1WeUYiYonHJduNjw8DEFVrcx9dmMsB5vjKGbl3oIeQYRgn68b1AA1xyY1OQH+d2mSPOpXFnfCILhULUdokM2JewBI2+OcBMiDI4KugBf7DD+lb+IwVsOOjJTnAe8xpZu9+M697VK4d5MtpmKc4bRh6J2FuPCKKieiXNo+nUwTT7MJGF/YeXsUck4L9pyS32Lw7EN54L6DWbJ+O5/TXRbg64U8gozumGvvL4JoGJ9Qjwb325xF9/r9xyqYzVhUavnGZPWAxlJylPgmX0N288x/QuUHKTPbKJGvOvDr7k7lPoHlf3jEYm6v5Ci2Gc8/5MsSKxpa7KRv6iiEIfr3v06hdKAzcGMa72UigBPnUplP4hYscFJU1rQ7a+ikgHfIRl+aaium62XmHDQWiCZ+lPEGWC5u7m0QGzVHjjTAuZBYSJQvGUCax5+A6OGnoqD8MnDfdsxb8xaSNrrH6nZ3ilUeeWJM4iRa92jdFELB7xDACIbFDQtM/dc3ILVdUOznEKa9qdtKqN9SPO+wUvyn39743P/ULKQnn6i70aBeaHrKx4PsVF5IgNzbquaox/cTfTe7o9B9goBzNzHHDUw5Aj1pP7I+e8PrQFYNxWumX9SthyNUxty5g1hw+3NUrlA0b6pc1hc8fzVwXxAjDSDgdLMs38UaASx28Zw="
